jaenyyyy/final-2

matdori/src/main/java/com/kh/matdori/MatdoriApplication.java
matdori/src/main/java/com/kh/matdori/ServletInitializer.java

matdori 패키지 생성

---

matdori/pom.xml
matdori/src/main/java/com/kh/matdori/configuration/EmailConfiguration.java
matdori/src/main/java/com/kh/matdori/configuration/EmailProperties.java
matdori/src/main/java/com/kh/matdori/configuration/EncryptConfiguration.java
matdori/src/main/java/com/kh/matdori/controller/Test01.java
matdori/src/main/java/com/kh/matdori/dao/Test01.java
matdori/src/main/java/com/kh/matdori/dto/Test01.java
matdori/src/main/java/com/kh/matdori/error/Test01.java
matdori/src/main/java/com/kh/matdori/interceptor/Test01.java
matdori/src/main/java/com/kh/matdori/rest/Test01.java
matdori/src/main/java/com/kh/matdori/service/Test01.java
matdori/src/main/java/com/kh/matdori/vo/Test01.java
matdori/src/main/resources/application.properties

패키지 생성용 test파일 업로드 및 pom추가

---

matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/CustomerBlockDto.java
matdori/src/main/java/com/kh/matdori/dto/CustomerDto.java
matdori/src/main/resources/mybatis/customer-mapper.xml

(mybatis 폴더 생성) customer 초기 생성 중

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/controller/HomeController.java
matdori/src/main/java/com/kh/matdori/controller/Test01.java
matdori/src/main/java/com/kh/matdori/dto/Test01.java
matdori/src/main/java/com/kh/matdori/error/AuthorityException.java
matdori/src/main/java/com/kh/matdori/error/ExceptionControllerAdvice.java
matdori/src/main/java/com/kh/matdori/error/NoTargetException.java
matdori/src/main/java/com/kh/matdori/error/Test01.java
matdori/src/main/java/com/kh/matdori/interceptor/Test01.java
matdori/src/main/java/com/kh/matdori/rest/Test01.java
matdori/src/main/java/com/kh/matdori/service/Test01.java
matdori/src/main/java/com/kh/matdori/vo/Test01.java
matdori/src/main/webapp/WEB-INF/views/error/500.jsp
matdori/src/main/webapp/WEB-INF/views/error/authority.jsp
matdori/src/main/webapp/WEB-INF/views/error/noTarget.jsp
matdori/src/main/webapp/WEB-INF/views/home.jsp
matdori/src/main/webapp/WEB-INF/views/template/footer.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

error 패키지 추가

---

matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/resources/mybatis/customer-mapper.xml

CustomerDao, mapper 생성중

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/resources/application.properties
matdori/src/main/resources/mybatis/customer-mapper.xml

customer controller 작성중

---

matdori/src/main/java/com/kh/matdori/configuration/FileUploadProperties.java
matdori/src/main/java/com/kh/matdori/controller/NoticeController.java
matdori/src/main/java/com/kh/matdori/controller/QnaController.java
matdori/src/main/java/com/kh/matdori/dao/AttachDao.java
matdori/src/main/java/com/kh/matdori/dao/AttachDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDao.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/QnaDao.java
matdori/src/main/java/com/kh/matdori/dao/QnaDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/NoticeDto.java
matdori/src/main/java/com/kh/matdori/dto/QnaDto.java
matdori/src/main/java/com/kh/matdori/vo/NoticePageVO.java
matdori/src/main/resources/mybatis/attach-mapper.xml
matdori/src/main/resources/mybatis/notice-mapper.xml
matdori/src/main/resources/mybatis/qna-mapper.xml
matdori/src/main/webapp/WEB-INF/views/notice/write.jsp
matdori/src/main/webapp/WEB-INF/views/qna/write.jsp

qna 게시판 / notice 게시판 CRUD 구현중

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/webapp/WEB-INF/views/customer/change.jsp

회원 탈퇴 페이지 구현 중

---

matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/QnaDaoImpl.java

게시판 dao 수정

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/resources/mybatis/customer-mapper.xml

회원정보변경 구현중 ..

---

matdori/src/main/webapp/WEB-INF/views/customer/change.jsp

customer 수정중

---

matdori/src/main/resources/mybatis/customer-mapper.xml

(mybatis)parameterType 수정

---

matdori/src/main/java/com/kh/matdori/controller/NoticeController.java
matdori/src/main/java/com/kh/matdori/controller/QnaController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDao.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/QnaDao.java
matdori/src/main/java/com/kh/matdori/dao/QnaDaoImpl.java
matdori/src/main/resources/mybatis/notice-mapper.xml
matdori/src/main/resources/mybatis/qna-mapper.xml
matdori/src/main/webapp/WEB-INF/views/customer/login.jsp
matdori/src/main/webapp/WEB-INF/views/home.jsp
matdori/src/main/webapp/WEB-INF/views/notice/detail.jsp
matdori/src/main/webapp/WEB-INF/views/notice/edit.jsp
matdori/src/main/webapp/WEB-INF/views/notice/list.jsp
matdori/src/main/webapp/WEB-INF/views/qna/detail.jsp
matdori/src/main/webapp/WEB-INF/views/qna/edit.jsp
matdori/src/main/webapp/WEB-INF/views/qna/list.jsp
matdori/src/main/webapp/WEB-INF/views/qna/write.jsp
matdori/src/main/webapp/WEB-INF/views/template/footer.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

notice / qna 백엔드 구현중 feat ) 귀요미 a 태그 ㅎㅎ

notice / qna 백엔드 구현중 feat ) 귀요미 a 태그 ㅎㅎ

---

matdori/src/main/java/com/kh/matdori/MatdoriApplication.java
matdori/src/main/java/com/kh/matdori/configuration/EmailConfiguration.java
matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/CustomerBlockDto.java
matdori/src/main/java/com/kh/matdori/dto/CustomerDto.java
matdori/src/main/java/com/kh/matdori/service/EmailService.java
matdori/src/main/java/com/kh/matdori/service/EmailServiceImpl.java
matdori/src/main/resources/mybatis/customer-mapper.xml
matdori/src/main/resources/templates/celebration.html
matdori/src/main/webapp/WEB-INF/views/customer/encryptPassword.jsp
matdori/src/main/webapp/WEB-INF/views/customer/encryptedPassword.jsp
matdori/src/main/webapp/WEB-INF/views/customer/findPw.jsp
matdori/src/main/webapp/WEB-INF/views/customer/findPwFinish.jsp
matdori/src/main/webapp/WEB-INF/views/home.jsp
matdori/src/test/java/matdori/CustomerJoinTest.java
matdori/src/test/java/matdori/CustomerLoginTest.java
matdori/src/test/java/matdori/Test01.java
matdori/src/test/java/matdori/Test02.java
matdori/src/test/java/matdori/Test03.java
matdori/src/test/java/matdori/Test04.java

이메일 인증 구현중

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/test/java/matdori/EmailTest01.java

이메일 구현 ing

---

matdori/src/main/java/com/kh/matdori/controller/NoticeController.java
matdori/src/main/java/com/kh/matdori/controller/QnaController.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDao.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/QnaDao.java
matdori/src/main/java/com/kh/matdori/dao/QnaDaoImpl.java
matdori/src/main/java/com/kh/matdori/vo/NoticePageVO.java
matdori/src/main/resources/mybatis/notice-mapper.xml
matdori/src/main/webapp/WEB-INF/views/notice/detail.jsp
matdori/src/main/webapp/WEB-INF/views/notice/edit.jsp
matdori/src/main/webapp/WEB-INF/views/notice/list.jsp
matdori/src/main/webapp/WEB-INF/views/notice/write.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

공지사항/ qna 게시판 페이지 네이션 구현중

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CertDao.java
matdori/src/main/java/com/kh/matdori/dao/CertDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/CertDto.java
matdori/src/main/java/com/kh/matdori/service/EmailServiceImpl.java
matdori/src/main/resources/mybatis/cert-mapper.xml
matdori/src/main/resources/mybatis/customer-mapper.xml
matdori/src/main/resources/templates/email.html
matdori/src/main/resources/templates/email2.html
matdori/src/main/webapp/WEB-INF/views/customer/login.jsp

일단 commit secure 일로와

---

matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/resources/mybatis/notice-mapper.xml

페이지네이션 구현중 근데 실패한

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/restcontroller/CertRestController.java
matdori/src/main/webapp/WEB-INF/views/customer/change.jsp
matdori/src/main/webapp/WEB-INF/views/customer/findPw.jsp
matdori/src/main/webapp/WEB-INF/views/customer/join.jsp
matdori/src/main/webapp/WEB-INF/views/customer/mypage.jsp

뭔가 이상하다 ..!

---

matdori/src/main/java/com/kh/matdori/controller/NoticeController.java
matdori/src/main/java/com/kh/matdori/controller/QnaController.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDao.java
matdori/src/main/java/com/kh/matdori/dao/NoticeDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/QnaDao.java
matdori/src/main/java/com/kh/matdori/dao/QnaDaoImpl.java
matdori/src/main/java/com/kh/matdori/vo/PaginationVO.java
matdori/src/main/resources/mybatis/notice-mapper.xml
matdori/src/main/resources/mybatis/qna-mapper.xml
matdori/src/main/webapp/WEB-INF/views/notice/detail.jsp
matdori/src/main/webapp/WEB-INF/views/notice/list.jsp
matdori/src/main/webapp/WEB-INF/views/qna/detail.jsp
matdori/src/main/webapp/WEB-INF/views/qna/list.jsp

공지사항 / qna 게시판 백 구현을 완료하였어요

---

matdori/src/main/webapp/WEB-INF/views/notice/list.jsp
matdori/src/main/webapp/WEB-INF/views/qna/list.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

qna/ 공지사항 백엔드 구현 완(프론트는 엉망진창)

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/resources/static/js/cert.js
matdori/src/main/webapp/WEB-INF/views/customer/findPw.jsp
matdori/src/main/webapp/WEB-INF/views/home.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

이메일 인증 후 비밀번호 재설정 구현중 ..

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CertDao.java
matdori/src/main/java/com/kh/matdori/dao/CertDaoImpl.java
matdori/src/main/java/com/kh/matdori/restcontroller/CertRestController.java
matdori/src/main/resources/application.properties
matdori/src/main/resources/mybatis/cert-mapper.xml
matdori/src/main/resources/mybatis/customer-mapper.xml
matdori/src/main/resources/static/js/cert.js
matdori/src/main/webapp/WEB-INF/views/customer/findPw.jsp
matdori/src/main/webapp/WEB-INF/views/customer/findPwFinish.jsp
matdori/src/main/webapp/WEB-INF/views/customer/join.jsp

logging 로깅로깅도 찍어보깅

---

matdori/pom.xml
matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/BusinessDao.java
matdori/src/main/java/com/kh/matdori/dao/BusinessDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/RestaurantDto.java
matdori/src/main/java/com/kh/matdori/restcontroller/BusinessRestController.java
matdori/src/main/resources/mybatis/business-mapper.xml

로그인(리코일)과 매장리스트구현

---

matdori/src/main/java/com/kh/matdori/configuration/EmptyStringControllerAdvice.java
matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/AdminDao.java
matdori/src/main/java/com/kh/matdori/dao/AdminDaoImpl.java
matdori/src/main/java/com/kh/matdori/vo/ResAdminVO.java
matdori/src/main/resources/application.properties
matdori/src/main/resources/mybatis/admin-mapper.xml
matdori/src/main/webapp/WEB-INF/views/admin/home.jsp
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/detail.jsp
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/list.jsp
matdori/src/main/webapp/WEB-INF/views/notice/list.jsp

관리자 기능 매장관리 구현중

---

matdori/src/main/java/com/kh/matdori/dto/CertDto.java
matdori/src/main/java/com/kh/matdori/restcontroller/BusinessRestController.java
matdori/src/main/java/com/kh/matdori/restcontroller/CertReactRestController.java
matdori/src/main/resources/mybatis/business-mapper.xml

이메일 인증 암호화 구현

---

matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDao.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java

오류나서 주석처리 하고 다시 올림 내일 말하기

---

matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/AdminDao.java
matdori/src/main/java/com/kh/matdori/dao/AdminDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/RestaurantDao.java
matdori/src/main/java/com/kh/matdori/dao/RestaurantDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/RestaurantAdminListDto.java
matdori/src/main/java/com/kh/matdori/restcontroller/AdminRestController.java
matdori/src/main/java/com/kh/matdori/restcontroller/RestaurantRestController.java
matdori/src/main/java/com/kh/matdori/vo/RestaurantJudgeVO.java
matdori/src/main/resources/mybatis/admin-mapper.xml
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/detail.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

restaurant + judge 합쳐서 vo 생성중임(임시)

restaurant + judge 합쳐서 vo 생성중임(임시)

---

matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/restcontroller/BusinessRestController.java

오류 주석처리 후 commit

---

matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/AdminDao.java
matdori/src/main/java/com/kh/matdori/dao/AdminDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/BusinessBlockDto.java
matdori/src/main/java/com/kh/matdori/dto/BusinessBlockListDto.java
matdori/src/main/resources/mybatis/admin-mapper.xml
matdori/src/main/webapp/WEB-INF/views/admin/business/BusBlockDetail.jsp
matdori/src/main/webapp/WEB-INF/views/admin/business/BusBlockList.jsp
matdori/src/main/webapp/WEB-INF/views/admin/business/judgeList.jsp
matdori/src/main/webapp/WEB-INF/views/admin/home.jsp

사업자 차단 구현중

---

matdori/src/main/java/com/kh/matdori/controller/ReviewController.java
matdori/src/main/java/com/kh/matdori/restcontroller/AdminRestController.java
matdori/src/main/java/com/kh/matdori/restcontroller/ReviewRestController.java
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/detail.jsp
matdori/src/main/webapp/WEB-INF/views/customer/detail.jsp
matdori/src/main/webapp/WEB-INF/views/customer/rezList.jsp

리뷰 작성 비동기로 옮겨서 구현중

---

matdori/src/main/java/com/kh/matdori/dao/AdminDao.java
matdori/src/main/java/com/kh/matdori/dao/AdminDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/RestaurantDao.java
matdori/src/main/java/com/kh/matdori/dao/RestaurantDaoImpl.java
matdori/src/main/java/com/kh/matdori/restcontroller/RestaurantRestController.java
matdori/src/main/java/com/kh/matdori/vo/RestaurantJudgeVO.java
matdori/src/main/resources/mybatis/admin-mapper.xml
matdori/src/main/webapp/WEB-INF/views/customer/rezList.jsp
matdori/src/main/webapp/WEB-INF/views/reservation/rezDetail.jsp

심사 진행 admin / 결제 구현중

---

matdori/src/main/java/com/kh/matdori/controller/AdminController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/restcontroller/CustomerRestController.java
matdori/src/main/resources/mybatis/admin-mapper.xml
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/detail.jsp
matdori/src/main/webapp/WEB-INF/views/admin/restaurant/list.jsp

심사 끝 결제 들어가야지

---

matdori/src/main/java/com/kh/matdori/controller/ReservationController.java
matdori/src/main/java/com/kh/matdori/vo/PaymentSumVO.java
matdori/src/main/webapp/WEB-INF/views/reservation/rezDetail.jsp

결제 구현을 위한 예약 끝

---

matdori/src/main/resources/static/css/test.css
matdori/src/main/webapp/WEB-INF/views/restaurant/detail.jsp
matdori/src/main/webapp/WEB-INF/views/template/header.jsp

레스토랑 상세 프론트 구현

---

matdori/src/main/java/com/kh/matdori/dao/RestaurantDao.java
matdori/src/main/java/com/kh/matdori/dao/RestaurantDaoImpl.java
matdori/src/main/java/com/kh/matdori/restcontroller/RestaurantRestController.java
matdori/src/main/resources/mybatis/restaurant-mapper.xml

오류주석처리하고 매장에 공지사항 등록 구현

---

matdori/src/main/resources/mybatis/restaurant-mapper.xml

브랜치 떔에요 .. ㅠ

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/CustomerDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/ReservationDao.java
matdori/src/main/java/com/kh/matdori/dao/ReservationDaoImpl.java
matdori/src/main/java/com/kh/matdori/vo/CusPaginationVO.java
matdori/src/main/resources/mybatis/reservation-mapper.xml

리뷰이미지 관련 오류 수정 
예약내역 페이지네이션 구현중

리뷰이미지 안뜨던거 오류수정

---

matdori/src/main/java/com/kh/matdori/controller/ReservationController.java
matdori/src/main/java/com/kh/matdori/dto/PaymentDto.java
matdori/src/main/resources/mybatis/payment-mapper.xml

rezNO를 가져와썽요 ㅎㅎ

---

matdori/src/main/java/com/kh/matdori/controller/CustomerController.java
matdori/src/main/java/com/kh/matdori/dao/ReservationDaoImpl.java
matdori/src/main/java/com/kh/matdori/dao/ReviewDao.java
matdori/src/main/java/com/kh/matdori/dao/ReviewDaoImpl.java
matdori/src/main/java/com/kh/matdori/dto/ReservationListDto.java
matdori/src/main/resources/mybatis/review-mapper.xml

리뷰페이지네이션 진행중

---

matdori/src/main/webapp/WEB-INF/views/customer/changePw.jsp
matdori/src/main/webapp/WEB-INF/views/customer/join.jsp

join jsp commit

---

matdori/src/main/java/com/kh/matdori/dao/ReservationDao.java
matdori/src/main/java/com/kh/matdori/dao/ReservationDaoImpl.java
matdori/src/main/webapp/WEB-INF/views/customer/rezList.jsp
matdori/src/main/webapp/WEB-INF/views/review/reviewListByCus.jsp

중복코드 주석처리, 리뷰 중복방지 기능구현

---

matdori/src/main/java/com/kh/matdori/controller/ReservationController.java

파이널 프로젝트 최종마무리(1차)

---

matdori/src/main/webapp/WEB-INF/views/customer/rezList.jsp

지금까지 했던거 커밋
